/* soapClient.cpp
   Generated by gSOAP 2.7.13 from server.h
   Copyright(C) 2000-2009, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#if defined(__BORLANDC__)
#pragma option push -w-8060
#pragma option push -w-8004
#endif
#include "soapH.h"

SOAP_SOURCE_STAMP("@(#) soapClient.cpp ver 2.7.13 2011-07-26 12:24:25 GMT")


SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__GetUsersForTitle(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns3__GetUsersForTitle *ns3__GetUsersForTitle, _ns3__GetUsersForTitleResponse *ns3__GetUsersForTitleResponse)
{	struct __ns1__GetUsersForTitle soap_tmp___ns1__GetUsersForTitle;
	if (!soap_endpoint)
		soap_endpoint = "https://rajkumars/iZINE.Web.MVC/server.svc";
	if (!soap_action)
		soap_action = "http://izine-publish.net/server/GetUsersForTitle";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__GetUsersForTitle.ns3__GetUsersForTitle = ns3__GetUsersForTitle;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__GetUsersForTitle(soap, &soap_tmp___ns1__GetUsersForTitle);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__GetUsersForTitle(soap, &soap_tmp___ns1__GetUsersForTitle, "-ns1:GetUsersForTitle", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__GetUsersForTitle(soap, &soap_tmp___ns1__GetUsersForTitle, "-ns1:GetUsersForTitle", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns3__GetUsersForTitleResponse)
		return soap_closesock(soap);
	ns3__GetUsersForTitleResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns3__GetUsersForTitleResponse->soap_get(soap, "ns3:GetUsersForTitleResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__GetTaskStatusList(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns3__GetTaskStatusList *ns3__GetTaskStatusList, _ns3__GetTaskStatusListResponse *ns3__GetTaskStatusListResponse)
{	struct __ns1__GetTaskStatusList soap_tmp___ns1__GetTaskStatusList;
	if (!soap_endpoint)
		soap_endpoint = "https://rajkumars/iZINE.Web.MVC/server.svc";
	if (!soap_action)
		soap_action = "http://izine-publish.net/server/GetTaskStatusList";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__GetTaskStatusList.ns3__GetTaskStatusList = ns3__GetTaskStatusList;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__GetTaskStatusList(soap, &soap_tmp___ns1__GetTaskStatusList);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__GetTaskStatusList(soap, &soap_tmp___ns1__GetTaskStatusList, "-ns1:GetTaskStatusList", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__GetTaskStatusList(soap, &soap_tmp___ns1__GetTaskStatusList, "-ns1:GetTaskStatusList", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns3__GetTaskStatusListResponse)
		return soap_closesock(soap);
	ns3__GetTaskStatusListResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns3__GetTaskStatusListResponse->soap_get(soap, "ns3:GetTaskStatusListResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__CreateTask(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns3__CreateTask *ns3__CreateTask, _ns3__CreateTaskResponse *ns3__CreateTaskResponse)
{	struct __ns1__CreateTask soap_tmp___ns1__CreateTask;
	if (!soap_endpoint)
		soap_endpoint = "https://rajkumars/iZINE.Web.MVC/server.svc";
	if (!soap_action)
		soap_action = "http://izine-publish.net/server/CreateTask";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__CreateTask.ns3__CreateTask = ns3__CreateTask;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__CreateTask(soap, &soap_tmp___ns1__CreateTask);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__CreateTask(soap, &soap_tmp___ns1__CreateTask, "-ns1:CreateTask", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__CreateTask(soap, &soap_tmp___ns1__CreateTask, "-ns1:CreateTask", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns3__CreateTaskResponse)
		return soap_closesock(soap);
	ns3__CreateTaskResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns3__CreateTaskResponse->soap_get(soap, "ns3:CreateTaskResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__GetTaskCategoryList(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns3__GetTaskCategoryList *ns3__GetTaskCategoryList, _ns3__GetTaskCategoryListResponse *ns3__GetTaskCategoryListResponse)
{	struct __ns1__GetTaskCategoryList soap_tmp___ns1__GetTaskCategoryList;
	if (!soap_endpoint)
		soap_endpoint = "https://rajkumars/iZINE.Web.MVC/server.svc";
	if (!soap_action)
		soap_action = "http://izine-publish.net/server/GetTaskCategoryList";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__GetTaskCategoryList.ns3__GetTaskCategoryList = ns3__GetTaskCategoryList;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__GetTaskCategoryList(soap, &soap_tmp___ns1__GetTaskCategoryList);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__GetTaskCategoryList(soap, &soap_tmp___ns1__GetTaskCategoryList, "-ns1:GetTaskCategoryList", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__GetTaskCategoryList(soap, &soap_tmp___ns1__GetTaskCategoryList, "-ns1:GetTaskCategoryList", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns3__GetTaskCategoryListResponse)
		return soap_closesock(soap);
	ns3__GetTaskCategoryListResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns3__GetTaskCategoryListResponse->soap_get(soap, "ns3:GetTaskCategoryListResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__UpdateTask(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns3__UpdateTask *ns3__UpdateTask, _ns3__UpdateTaskResponse *ns3__UpdateTaskResponse)
{	struct __ns1__UpdateTask soap_tmp___ns1__UpdateTask;
	if (!soap_endpoint)
		soap_endpoint = "https://rajkumars/iZINE.Web.MVC/server.svc";
	if (!soap_action)
		soap_action = "http://izine-publish.net/server/UpdateTask";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__UpdateTask.ns3__UpdateTask = ns3__UpdateTask;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__UpdateTask(soap, &soap_tmp___ns1__UpdateTask);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__UpdateTask(soap, &soap_tmp___ns1__UpdateTask, "-ns1:UpdateTask", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__UpdateTask(soap, &soap_tmp___ns1__UpdateTask, "-ns1:UpdateTask", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns3__UpdateTaskResponse)
		return soap_closesock(soap);
	ns3__UpdateTaskResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns3__UpdateTaskResponse->soap_get(soap, "ns3:UpdateTaskResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__GetTaskHistory(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns3__GetTaskHistory *ns3__GetTaskHistory, _ns3__GetTaskHistoryResponse *ns3__GetTaskHistoryResponse)
{	struct __ns1__GetTaskHistory soap_tmp___ns1__GetTaskHistory;
	if (!soap_endpoint)
		soap_endpoint = "https://rajkumars/iZINE.Web.MVC/server.svc";
	if (!soap_action)
		soap_action = "http://izine-publish.net/server/GetTaskHistory";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__GetTaskHistory.ns3__GetTaskHistory = ns3__GetTaskHistory;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__GetTaskHistory(soap, &soap_tmp___ns1__GetTaskHistory);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__GetTaskHistory(soap, &soap_tmp___ns1__GetTaskHistory, "-ns1:GetTaskHistory", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__GetTaskHistory(soap, &soap_tmp___ns1__GetTaskHistory, "-ns1:GetTaskHistory", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns3__GetTaskHistoryResponse)
		return soap_closesock(soap);
	ns3__GetTaskHistoryResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns3__GetTaskHistoryResponse->soap_get(soap, "ns3:GetTaskHistoryResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__DeleteTask(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns3__DeleteTask *ns3__DeleteTask, _ns3__DeleteTaskResponse *ns3__DeleteTaskResponse)
{	struct __ns1__DeleteTask soap_tmp___ns1__DeleteTask;
	if (!soap_endpoint)
		soap_endpoint = "https://rajkumars/iZINE.Web.MVC/server.svc";
	if (!soap_action)
		soap_action = "http://izine-publish.net/server/DeleteTask";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__DeleteTask.ns3__DeleteTask = ns3__DeleteTask;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__DeleteTask(soap, &soap_tmp___ns1__DeleteTask);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__DeleteTask(soap, &soap_tmp___ns1__DeleteTask, "-ns1:DeleteTask", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__DeleteTask(soap, &soap_tmp___ns1__DeleteTask, "-ns1:DeleteTask", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns3__DeleteTaskResponse)
		return soap_closesock(soap);
	ns3__DeleteTaskResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns3__DeleteTaskResponse->soap_get(soap, "ns3:DeleteTaskResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__Login(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns3__Login *ns3__Login, _ns3__LoginResponse *ns3__LoginResponse)
{	struct __ns1__Login soap_tmp___ns1__Login;
	if (!soap_endpoint)
		soap_endpoint = "https://rajkumars/iZINE.Web.MVC/server.svc";
	if (!soap_action)
		soap_action = "http://izine-publish.net/server/Login";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__Login.ns3__Login = ns3__Login;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__Login(soap, &soap_tmp___ns1__Login);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__Login(soap, &soap_tmp___ns1__Login, "-ns1:Login", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__Login(soap, &soap_tmp___ns1__Login, "-ns1:Login", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns3__LoginResponse)
		return soap_closesock(soap);
	ns3__LoginResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns3__LoginResponse->soap_get(soap, "ns3:LoginResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__GetTitleList(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns3__GetTitleList *ns3__GetTitleList, _ns3__GetTitleListResponse *ns3__GetTitleListResponse)
{	struct __ns1__GetTitleList soap_tmp___ns1__GetTitleList;
	if (!soap_endpoint)
		soap_endpoint = "https://rajkumars/iZINE.Web.MVC/server.svc";
	if (!soap_action)
		soap_action = "http://izine-publish.net/server/GetTitleList";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__GetTitleList.ns3__GetTitleList = ns3__GetTitleList;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__GetTitleList(soap, &soap_tmp___ns1__GetTitleList);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__GetTitleList(soap, &soap_tmp___ns1__GetTitleList, "-ns1:GetTitleList", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__GetTitleList(soap, &soap_tmp___ns1__GetTitleList, "-ns1:GetTitleList", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns3__GetTitleListResponse)
		return soap_closesock(soap);
	ns3__GetTitleListResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns3__GetTitleListResponse->soap_get(soap, "ns3:GetTitleListResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__GetRole(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns3__GetRole *ns3__GetRole, _ns3__GetRoleResponse *ns3__GetRoleResponse)
{	struct __ns1__GetRole soap_tmp___ns1__GetRole;
	if (!soap_endpoint)
		soap_endpoint = "https://rajkumars/iZINE.Web.MVC/server.svc";
	if (!soap_action)
		soap_action = "http://izine-publish.net/server/GetRole";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__GetRole.ns3__GetRole = ns3__GetRole;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__GetRole(soap, &soap_tmp___ns1__GetRole);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__GetRole(soap, &soap_tmp___ns1__GetRole, "-ns1:GetRole", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__GetRole(soap, &soap_tmp___ns1__GetRole, "-ns1:GetRole", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns3__GetRoleResponse)
		return soap_closesock(soap);
	ns3__GetRoleResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns3__GetRoleResponse->soap_get(soap, "ns3:GetRoleResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__GetCommentList(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns3__GetCommentList *ns3__GetCommentList, _ns3__GetCommentListResponse *ns3__GetCommentListResponse)
{	struct __ns1__GetCommentList soap_tmp___ns1__GetCommentList;
	if (!soap_endpoint)
		soap_endpoint = "https://rajkumars/iZINE.Web.MVC/server.svc";
	if (!soap_action)
		soap_action = "http://izine-publish.net/server/GetCommentList";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__GetCommentList.ns3__GetCommentList = ns3__GetCommentList;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__GetCommentList(soap, &soap_tmp___ns1__GetCommentList);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__GetCommentList(soap, &soap_tmp___ns1__GetCommentList, "-ns1:GetCommentList", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__GetCommentList(soap, &soap_tmp___ns1__GetCommentList, "-ns1:GetCommentList", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns3__GetCommentListResponse)
		return soap_closesock(soap);
	ns3__GetCommentListResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns3__GetCommentListResponse->soap_get(soap, "ns3:GetCommentListResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__GetTags(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns3__GetTags *ns3__GetTags, _ns3__GetTagsResponse *ns3__GetTagsResponse)
{	struct __ns1__GetTags soap_tmp___ns1__GetTags;
	if (!soap_endpoint)
		soap_endpoint = "https://rajkumars/iZINE.Web.MVC/server.svc";
	if (!soap_action)
		soap_action = "http://izine-publish.net/server/GetTags";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__GetTags.ns3__GetTags = ns3__GetTags;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__GetTags(soap, &soap_tmp___ns1__GetTags);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__GetTags(soap, &soap_tmp___ns1__GetTags, "-ns1:GetTags", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__GetTags(soap, &soap_tmp___ns1__GetTags, "-ns1:GetTags", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns3__GetTagsResponse)
		return soap_closesock(soap);
	ns3__GetTagsResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns3__GetTagsResponse->soap_get(soap, "ns3:GetTagsResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__GetShelveList(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns3__GetShelveList *ns3__GetShelveList, _ns3__GetShelveListResponse *ns3__GetShelveListResponse)
{	struct __ns1__GetShelveList soap_tmp___ns1__GetShelveList;
	if (!soap_endpoint)
		soap_endpoint = "https://rajkumars/iZINE.Web.MVC/server.svc";
	if (!soap_action)
		soap_action = "http://izine-publish.net/server/GetShelveList";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__GetShelveList.ns3__GetShelveList = ns3__GetShelveList;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__GetShelveList(soap, &soap_tmp___ns1__GetShelveList);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__GetShelveList(soap, &soap_tmp___ns1__GetShelveList, "-ns1:GetShelveList", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__GetShelveList(soap, &soap_tmp___ns1__GetShelveList, "-ns1:GetShelveList", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns3__GetShelveListResponse)
		return soap_closesock(soap);
	ns3__GetShelveListResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns3__GetShelveListResponse->soap_get(soap, "ns3:GetShelveListResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__Logoff(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns3__Logoff *ns3__Logoff, _ns3__LogoffResponse *ns3__LogoffResponse)
{	struct __ns1__Logoff soap_tmp___ns1__Logoff;
	if (!soap_endpoint)
		soap_endpoint = "https://rajkumars/iZINE.Web.MVC/server.svc";
	if (!soap_action)
		soap_action = "http://izine-publish.net/server/Logoff";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__Logoff.ns3__Logoff = ns3__Logoff;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__Logoff(soap, &soap_tmp___ns1__Logoff);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__Logoff(soap, &soap_tmp___ns1__Logoff, "-ns1:Logoff", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__Logoff(soap, &soap_tmp___ns1__Logoff, "-ns1:Logoff", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns3__LogoffResponse)
		return soap_closesock(soap);
	ns3__LogoffResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns3__LogoffResponse->soap_get(soap, "ns3:LogoffResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__GetUser(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns3__GetUser *ns3__GetUser, _ns3__GetUserResponse *ns3__GetUserResponse)
{	struct __ns1__GetUser soap_tmp___ns1__GetUser;
	if (!soap_endpoint)
		soap_endpoint = "https://rajkumars/iZINE.Web.MVC/server.svc";
	if (!soap_action)
		soap_action = "http://izine-publish.net/server/GetUser";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__GetUser.ns3__GetUser = ns3__GetUser;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__GetUser(soap, &soap_tmp___ns1__GetUser);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__GetUser(soap, &soap_tmp___ns1__GetUser, "-ns1:GetUser", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__GetUser(soap, &soap_tmp___ns1__GetUser, "-ns1:GetUser", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns3__GetUserResponse)
		return soap_closesock(soap);
	ns3__GetUserResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns3__GetUserResponse->soap_get(soap, "ns3:GetUserResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__GetThumbnail(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns3__GetThumbnail *ns3__GetThumbnail, _ns3__GetThumbnailResponse *ns3__GetThumbnailResponse)
{	struct __ns1__GetThumbnail soap_tmp___ns1__GetThumbnail;
	if (!soap_endpoint)
		soap_endpoint = "https://rajkumars/iZINE.Web.MVC/server.svc";
	if (!soap_action)
		soap_action = "http://izine-publish.net/server/GetThumbnail";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__GetThumbnail.ns3__GetThumbnail = ns3__GetThumbnail;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__GetThumbnail(soap, &soap_tmp___ns1__GetThumbnail);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__GetThumbnail(soap, &soap_tmp___ns1__GetThumbnail, "-ns1:GetThumbnail", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__GetThumbnail(soap, &soap_tmp___ns1__GetThumbnail, "-ns1:GetThumbnail", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns3__GetThumbnailResponse)
		return soap_closesock(soap);
	ns3__GetThumbnailResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns3__GetThumbnailResponse->soap_get(soap, "ns3:GetThumbnailResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__LockAsset(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns3__LockAsset *ns3__LockAsset, _ns3__LockAssetResponse *ns3__LockAssetResponse)
{	struct __ns1__LockAsset soap_tmp___ns1__LockAsset;
	if (!soap_endpoint)
		soap_endpoint = "https://rajkumars/iZINE.Web.MVC/server.svc";
	if (!soap_action)
		soap_action = "http://izine-publish.net/server/LockAsset";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__LockAsset.ns3__LockAsset = ns3__LockAsset;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__LockAsset(soap, &soap_tmp___ns1__LockAsset);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__LockAsset(soap, &soap_tmp___ns1__LockAsset, "-ns1:LockAsset", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__LockAsset(soap, &soap_tmp___ns1__LockAsset, "-ns1:LockAsset", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns3__LockAssetResponse)
		return soap_closesock(soap);
	ns3__LockAssetResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns3__LockAssetResponse->soap_get(soap, "ns3:LockAssetResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__UnlockAsset(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns3__UnlockAsset *ns3__UnlockAsset, _ns3__UnlockAssetResponse *ns3__UnlockAssetResponse)
{	struct __ns1__UnlockAsset soap_tmp___ns1__UnlockAsset;
	if (!soap_endpoint)
		soap_endpoint = "https://rajkumars/iZINE.Web.MVC/server.svc";
	if (!soap_action)
		soap_action = "http://izine-publish.net/server/UnlockAsset";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__UnlockAsset.ns3__UnlockAsset = ns3__UnlockAsset;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__UnlockAsset(soap, &soap_tmp___ns1__UnlockAsset);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__UnlockAsset(soap, &soap_tmp___ns1__UnlockAsset, "-ns1:UnlockAsset", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__UnlockAsset(soap, &soap_tmp___ns1__UnlockAsset, "-ns1:UnlockAsset", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns3__UnlockAssetResponse)
		return soap_closesock(soap);
	ns3__UnlockAssetResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns3__UnlockAssetResponse->soap_get(soap, "ns3:UnlockAssetResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__DeleteAsset(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns3__DeleteAsset *ns3__DeleteAsset, _ns3__DeleteAssetResponse *ns3__DeleteAssetResponse)
{	struct __ns1__DeleteAsset soap_tmp___ns1__DeleteAsset;
	if (!soap_endpoint)
		soap_endpoint = "https://rajkumars/iZINE.Web.MVC/server.svc";
	if (!soap_action)
		soap_action = "http://izine-publish.net/server/DeleteAsset";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__DeleteAsset.ns3__DeleteAsset = ns3__DeleteAsset;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__DeleteAsset(soap, &soap_tmp___ns1__DeleteAsset);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__DeleteAsset(soap, &soap_tmp___ns1__DeleteAsset, "-ns1:DeleteAsset", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__DeleteAsset(soap, &soap_tmp___ns1__DeleteAsset, "-ns1:DeleteAsset", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns3__DeleteAssetResponse)
		return soap_closesock(soap);
	ns3__DeleteAssetResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns3__DeleteAssetResponse->soap_get(soap, "ns3:DeleteAssetResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__CreateAsset(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns3__CreateAsset *ns3__CreateAsset, _ns3__CreateAssetResponse *ns3__CreateAssetResponse)
{	struct __ns1__CreateAsset soap_tmp___ns1__CreateAsset;
	if (!soap_endpoint)
		soap_endpoint = "https://rajkumars/iZINE.Web.MVC/server.svc";
	if (!soap_action)
		soap_action = "http://izine-publish.net/server/CreateAsset";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__CreateAsset.ns3__CreateAsset = ns3__CreateAsset;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__CreateAsset(soap, &soap_tmp___ns1__CreateAsset);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__CreateAsset(soap, &soap_tmp___ns1__CreateAsset, "-ns1:CreateAsset", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__CreateAsset(soap, &soap_tmp___ns1__CreateAsset, "-ns1:CreateAsset", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns3__CreateAssetResponse)
		return soap_closesock(soap);
	ns3__CreateAssetResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns3__CreateAssetResponse->soap_get(soap, "ns3:CreateAssetResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__UpdateAssetName(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns3__UpdateAssetName *ns3__UpdateAssetName, _ns3__UpdateAssetNameResponse *ns3__UpdateAssetNameResponse)
{	struct __ns1__UpdateAssetName soap_tmp___ns1__UpdateAssetName;
	if (!soap_endpoint)
		soap_endpoint = "https://rajkumars/iZINE.Web.MVC/server.svc";
	if (!soap_action)
		soap_action = "http://izine-publish.net/server/UpdateAssetName";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__UpdateAssetName.ns3__UpdateAssetName = ns3__UpdateAssetName;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__UpdateAssetName(soap, &soap_tmp___ns1__UpdateAssetName);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__UpdateAssetName(soap, &soap_tmp___ns1__UpdateAssetName, "-ns1:UpdateAssetName", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__UpdateAssetName(soap, &soap_tmp___ns1__UpdateAssetName, "-ns1:UpdateAssetName", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns3__UpdateAssetNameResponse)
		return soap_closesock(soap);
	ns3__UpdateAssetNameResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns3__UpdateAssetNameResponse->soap_get(soap, "ns3:UpdateAssetNameResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__CanUpdateAssetName(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns3__CanUpdateAssetName *ns3__CanUpdateAssetName, _ns3__CanUpdateAssetNameResponse *ns3__CanUpdateAssetNameResponse)
{	struct __ns1__CanUpdateAssetName soap_tmp___ns1__CanUpdateAssetName;
	if (!soap_endpoint)
		soap_endpoint = "https://rajkumars/iZINE.Web.MVC/server.svc";
	if (!soap_action)
		soap_action = "http://izine-publish.net/server/CanUpdateAssetName";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__CanUpdateAssetName.ns3__CanUpdateAssetName = ns3__CanUpdateAssetName;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__CanUpdateAssetName(soap, &soap_tmp___ns1__CanUpdateAssetName);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__CanUpdateAssetName(soap, &soap_tmp___ns1__CanUpdateAssetName, "-ns1:CanUpdateAssetName", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__CanUpdateAssetName(soap, &soap_tmp___ns1__CanUpdateAssetName, "-ns1:CanUpdateAssetName", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns3__CanUpdateAssetNameResponse)
		return soap_closesock(soap);
	ns3__CanUpdateAssetNameResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns3__CanUpdateAssetNameResponse->soap_get(soap, "ns3:CanUpdateAssetNameResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__GetAsset(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns3__GetAsset *ns3__GetAsset, _ns3__GetAssetResponse *ns3__GetAssetResponse)
{	struct __ns1__GetAsset soap_tmp___ns1__GetAsset;
	if (!soap_endpoint)
		soap_endpoint = "https://rajkumars/iZINE.Web.MVC/server.svc";
	if (!soap_action)
		soap_action = "http://izine-publish.net/server/GetAsset";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__GetAsset.ns3__GetAsset = ns3__GetAsset;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__GetAsset(soap, &soap_tmp___ns1__GetAsset);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__GetAsset(soap, &soap_tmp___ns1__GetAsset, "-ns1:GetAsset", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__GetAsset(soap, &soap_tmp___ns1__GetAsset, "-ns1:GetAsset", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns3__GetAssetResponse)
		return soap_closesock(soap);
	ns3__GetAssetResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns3__GetAssetResponse->soap_get(soap, "ns3:GetAssetResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__UploadPDF(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns3__UploadPDF *ns3__UploadPDF, _ns3__UploadPDFResponse *ns3__UploadPDFResponse)
{	struct __ns1__UploadPDF soap_tmp___ns1__UploadPDF;
	if (!soap_endpoint)
		soap_endpoint = "https://rajkumars/iZINE.Web.MVC/server.svc";
	if (!soap_action)
		soap_action = "http://izine-publish.net/server/UploadPDF";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__UploadPDF.ns3__UploadPDF = ns3__UploadPDF;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__UploadPDF(soap, &soap_tmp___ns1__UploadPDF);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__UploadPDF(soap, &soap_tmp___ns1__UploadPDF, "-ns1:UploadPDF", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__UploadPDF(soap, &soap_tmp___ns1__UploadPDF, "-ns1:UploadPDF", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns3__UploadPDFResponse)
		return soap_closesock(soap);
	ns3__UploadPDFResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns3__UploadPDFResponse->soap_get(soap, "ns3:UploadPDFResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__UploadPage(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns3__UploadPage *ns3__UploadPage, _ns3__UploadPageResponse *ns3__UploadPageResponse)
{	struct __ns1__UploadPage soap_tmp___ns1__UploadPage;
	if (!soap_endpoint)
		soap_endpoint = "https://rajkumars/iZINE.Web.MVC/server.svc";
	if (!soap_action)
		soap_action = "http://izine-publish.net/server/UploadPage";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__UploadPage.ns3__UploadPage = ns3__UploadPage;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__UploadPage(soap, &soap_tmp___ns1__UploadPage);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__UploadPage(soap, &soap_tmp___ns1__UploadPage, "-ns1:UploadPage", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__UploadPage(soap, &soap_tmp___ns1__UploadPage, "-ns1:UploadPage", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns3__UploadPageResponse)
		return soap_closesock(soap);
	ns3__UploadPageResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns3__UploadPageResponse->soap_get(soap, "ns3:UploadPageResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__UploadVersion(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns3__UploadVersion *ns3__UploadVersion, _ns3__UploadVersionResponse *ns3__UploadVersionResponse)
{	struct __ns1__UploadVersion soap_tmp___ns1__UploadVersion;
	if (!soap_endpoint)
		soap_endpoint = "https://rajkumars/iZINE.Web.MVC/server.svc";
	if (!soap_action)
		soap_action = "http://izine-publish.net/server/UploadVersion";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__UploadVersion.ns3__UploadVersion = ns3__UploadVersion;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__UploadVersion(soap, &soap_tmp___ns1__UploadVersion);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__UploadVersion(soap, &soap_tmp___ns1__UploadVersion, "-ns1:UploadVersion", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__UploadVersion(soap, &soap_tmp___ns1__UploadVersion, "-ns1:UploadVersion", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns3__UploadVersionResponse)
		return soap_closesock(soap);
	ns3__UploadVersionResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns3__UploadVersionResponse->soap_get(soap, "ns3:UploadVersionResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__UploadExport(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns3__UploadExport *ns3__UploadExport, _ns3__UploadExportResponse *ns3__UploadExportResponse)
{	struct __ns1__UploadExport soap_tmp___ns1__UploadExport;
	if (!soap_endpoint)
		soap_endpoint = "https://rajkumars/iZINE.Web.MVC/server.svc";
	if (!soap_action)
		soap_action = "http://izine-publish.net/server/UploadExport";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__UploadExport.ns3__UploadExport = ns3__UploadExport;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__UploadExport(soap, &soap_tmp___ns1__UploadExport);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__UploadExport(soap, &soap_tmp___ns1__UploadExport, "-ns1:UploadExport", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__UploadExport(soap, &soap_tmp___ns1__UploadExport, "-ns1:UploadExport", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns3__UploadExportResponse)
		return soap_closesock(soap);
	ns3__UploadExportResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns3__UploadExportResponse->soap_get(soap, "ns3:UploadExportResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__UnlinkAsset(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns3__UnlinkAsset *ns3__UnlinkAsset, _ns3__UnlinkAssetResponse *ns3__UnlinkAssetResponse)
{	struct __ns1__UnlinkAsset soap_tmp___ns1__UnlinkAsset;
	if (!soap_endpoint)
		soap_endpoint = "https://rajkumars/iZINE.Web.MVC/server.svc";
	if (!soap_action)
		soap_action = "http://izine-publish.net/server/UnlinkAsset";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__UnlinkAsset.ns3__UnlinkAsset = ns3__UnlinkAsset;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__UnlinkAsset(soap, &soap_tmp___ns1__UnlinkAsset);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__UnlinkAsset(soap, &soap_tmp___ns1__UnlinkAsset, "-ns1:UnlinkAsset", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__UnlinkAsset(soap, &soap_tmp___ns1__UnlinkAsset, "-ns1:UnlinkAsset", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns3__UnlinkAssetResponse)
		return soap_closesock(soap);
	ns3__UnlinkAssetResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns3__UnlinkAssetResponse->soap_get(soap, "ns3:UnlinkAssetResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__RelinkAsset(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns3__RelinkAsset *ns3__RelinkAsset, _ns3__RelinkAssetResponse *ns3__RelinkAssetResponse)
{	struct __ns1__RelinkAsset soap_tmp___ns1__RelinkAsset;
	if (!soap_endpoint)
		soap_endpoint = "https://rajkumars/iZINE.Web.MVC/server.svc";
	if (!soap_action)
		soap_action = "http://izine-publish.net/server/RelinkAsset";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__RelinkAsset.ns3__RelinkAsset = ns3__RelinkAsset;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__RelinkAsset(soap, &soap_tmp___ns1__RelinkAsset);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__RelinkAsset(soap, &soap_tmp___ns1__RelinkAsset, "-ns1:RelinkAsset", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__RelinkAsset(soap, &soap_tmp___ns1__RelinkAsset, "-ns1:RelinkAsset", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns3__RelinkAssetResponse)
		return soap_closesock(soap);
	ns3__RelinkAssetResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns3__RelinkAssetResponse->soap_get(soap, "ns3:RelinkAssetResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__GetEditionTaskList(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns3__GetEditionTaskList *ns3__GetEditionTaskList, _ns3__GetEditionTaskListResponse *ns3__GetEditionTaskListResponse)
{	struct __ns1__GetEditionTaskList soap_tmp___ns1__GetEditionTaskList;
	if (!soap_endpoint)
		soap_endpoint = "https://rajkumars/iZINE.Web.MVC/server.svc";
	if (!soap_action)
		soap_action = "http://izine-publish.net/server/GetEditionTaskList";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__GetEditionTaskList.ns3__GetEditionTaskList = ns3__GetEditionTaskList;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__GetEditionTaskList(soap, &soap_tmp___ns1__GetEditionTaskList);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__GetEditionTaskList(soap, &soap_tmp___ns1__GetEditionTaskList, "-ns1:GetEditionTaskList", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__GetEditionTaskList(soap, &soap_tmp___ns1__GetEditionTaskList, "-ns1:GetEditionTaskList", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns3__GetEditionTaskListResponse)
		return soap_closesock(soap);
	ns3__GetEditionTaskListResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns3__GetEditionTaskListResponse->soap_get(soap, "ns3:GetEditionTaskListResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__CheckOutAsset(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns3__CheckOutAsset *ns3__CheckOutAsset, _ns3__CheckOutAssetResponse *ns3__CheckOutAssetResponse)
{	struct __ns1__CheckOutAsset soap_tmp___ns1__CheckOutAsset;
	if (!soap_endpoint)
		soap_endpoint = "https://rajkumars/iZINE.Web.MVC/server.svc";
	if (!soap_action)
		soap_action = "http://izine-publish.net/server/CheckOutAsset";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__CheckOutAsset.ns3__CheckOutAsset = ns3__CheckOutAsset;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__CheckOutAsset(soap, &soap_tmp___ns1__CheckOutAsset);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__CheckOutAsset(soap, &soap_tmp___ns1__CheckOutAsset, "-ns1:CheckOutAsset", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__CheckOutAsset(soap, &soap_tmp___ns1__CheckOutAsset, "-ns1:CheckOutAsset", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns3__CheckOutAssetResponse)
		return soap_closesock(soap);
	ns3__CheckOutAssetResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns3__CheckOutAssetResponse->soap_get(soap, "ns3:CheckOutAssetResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__GetEditionsByTitle(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns3__GetEditionsByTitle *ns3__GetEditionsByTitle, _ns3__GetEditionsByTitleResponse *ns3__GetEditionsByTitleResponse)
{	struct __ns1__GetEditionsByTitle soap_tmp___ns1__GetEditionsByTitle;
	if (!soap_endpoint)
		soap_endpoint = "https://rajkumars/iZINE.Web.MVC/server.svc";
	if (!soap_action)
		soap_action = "http://izine-publish.net/server/GetEditionsByTitle";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__GetEditionsByTitle.ns3__GetEditionsByTitle = ns3__GetEditionsByTitle;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__GetEditionsByTitle(soap, &soap_tmp___ns1__GetEditionsByTitle);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__GetEditionsByTitle(soap, &soap_tmp___ns1__GetEditionsByTitle, "-ns1:GetEditionsByTitle", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__GetEditionsByTitle(soap, &soap_tmp___ns1__GetEditionsByTitle, "-ns1:GetEditionsByTitle", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns3__GetEditionsByTitleResponse)
		return soap_closesock(soap);
	ns3__GetEditionsByTitleResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns3__GetEditionsByTitleResponse->soap_get(soap, "ns3:GetEditionsByTitleResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__GetStatusByTitle(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns3__GetStatusByTitle *ns3__GetStatusByTitle, _ns3__GetStatusByTitleResponse *ns3__GetStatusByTitleResponse)
{	struct __ns1__GetStatusByTitle soap_tmp___ns1__GetStatusByTitle;
	if (!soap_endpoint)
		soap_endpoint = "https://rajkumars/iZINE.Web.MVC/server.svc";
	if (!soap_action)
		soap_action = "http://izine-publish.net/server/GetStatusByTitle";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__GetStatusByTitle.ns3__GetStatusByTitle = ns3__GetStatusByTitle;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__GetStatusByTitle(soap, &soap_tmp___ns1__GetStatusByTitle);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__GetStatusByTitle(soap, &soap_tmp___ns1__GetStatusByTitle, "-ns1:GetStatusByTitle", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__GetStatusByTitle(soap, &soap_tmp___ns1__GetStatusByTitle, "-ns1:GetStatusByTitle", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns3__GetStatusByTitleResponse)
		return soap_closesock(soap);
	ns3__GetStatusByTitleResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns3__GetStatusByTitleResponse->soap_get(soap, "ns3:GetStatusByTitleResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__GetAssetList(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns3__GetAssetList *ns3__GetAssetList, _ns3__GetAssetListResponse *ns3__GetAssetListResponse)
{	struct __ns1__GetAssetList soap_tmp___ns1__GetAssetList;
	if (!soap_endpoint)
		soap_endpoint = "https://rajkumars/iZINE.Web.MVC/server.svc";
	if (!soap_action)
		soap_action = "http://izine-publish.net/server/GetAssetList";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__GetAssetList.ns3__GetAssetList = ns3__GetAssetList;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__GetAssetList(soap, &soap_tmp___ns1__GetAssetList);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__GetAssetList(soap, &soap_tmp___ns1__GetAssetList, "-ns1:GetAssetList", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__GetAssetList(soap, &soap_tmp___ns1__GetAssetList, "-ns1:GetAssetList", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns3__GetAssetListResponse)
		return soap_closesock(soap);
	ns3__GetAssetListResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns3__GetAssetListResponse->soap_get(soap, "ns3:GetAssetListResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__UpdateAsset(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns3__UpdateAsset *ns3__UpdateAsset, _ns3__UpdateAssetResponse *ns3__UpdateAssetResponse)
{	struct __ns1__UpdateAsset soap_tmp___ns1__UpdateAsset;
	if (!soap_endpoint)
		soap_endpoint = "https://rajkumars/iZINE.Web.MVC/server.svc";
	if (!soap_action)
		soap_action = "http://izine-publish.net/server/UpdateAsset";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__UpdateAsset.ns3__UpdateAsset = ns3__UpdateAsset;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__UpdateAsset(soap, &soap_tmp___ns1__UpdateAsset);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__UpdateAsset(soap, &soap_tmp___ns1__UpdateAsset, "-ns1:UpdateAsset", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__UpdateAsset(soap, &soap_tmp___ns1__UpdateAsset, "-ns1:UpdateAsset", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns3__UpdateAssetResponse)
		return soap_closesock(soap);
	ns3__UpdateAssetResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns3__UpdateAssetResponse->soap_get(soap, "ns3:UpdateAssetResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__UpdateAssetStatus(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns3__UpdateAssetStatus *ns3__UpdateAssetStatus, _ns3__UpdateAssetStatusResponse *ns3__UpdateAssetStatusResponse)
{	struct __ns1__UpdateAssetStatus soap_tmp___ns1__UpdateAssetStatus;
	if (!soap_endpoint)
		soap_endpoint = "https://rajkumars/iZINE.Web.MVC/server.svc";
	if (!soap_action)
		soap_action = "http://izine-publish.net/server/UpdateAssetStatus";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__UpdateAssetStatus.ns3__UpdateAssetStatus = ns3__UpdateAssetStatus;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__UpdateAssetStatus(soap, &soap_tmp___ns1__UpdateAssetStatus);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__UpdateAssetStatus(soap, &soap_tmp___ns1__UpdateAssetStatus, "-ns1:UpdateAssetStatus", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__UpdateAssetStatus(soap, &soap_tmp___ns1__UpdateAssetStatus, "-ns1:UpdateAssetStatus", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns3__UpdateAssetStatusResponse)
		return soap_closesock(soap);
	ns3__UpdateAssetStatusResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns3__UpdateAssetStatusResponse->soap_get(soap, "ns3:UpdateAssetStatusResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__GetLock(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns3__GetLock *ns3__GetLock, _ns3__GetLockResponse *ns3__GetLockResponse)
{	struct __ns1__GetLock soap_tmp___ns1__GetLock;
	if (!soap_endpoint)
		soap_endpoint = "https://rajkumars/iZINE.Web.MVC/server.svc";
	if (!soap_action)
		soap_action = "http://izine-publish.net/server/GetLock";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__GetLock.ns3__GetLock = ns3__GetLock;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__GetLock(soap, &soap_tmp___ns1__GetLock);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__GetLock(soap, &soap_tmp___ns1__GetLock, "-ns1:GetLock", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__GetLock(soap, &soap_tmp___ns1__GetLock, "-ns1:GetLock", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns3__GetLockResponse)
		return soap_closesock(soap);
	ns3__GetLockResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns3__GetLockResponse->soap_get(soap, "ns3:GetLockResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__CheckInAsset(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns3__CheckInAsset *ns3__CheckInAsset, _ns3__CheckInAssetResponse *ns3__CheckInAssetResponse)
{	struct __ns1__CheckInAsset soap_tmp___ns1__CheckInAsset;
	if (!soap_endpoint)
		soap_endpoint = "https://rajkumars/iZINE.Web.MVC/server.svc";
	if (!soap_action)
		soap_action = "http://izine-publish.net/server/CheckInAsset";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__CheckInAsset.ns3__CheckInAsset = ns3__CheckInAsset;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__CheckInAsset(soap, &soap_tmp___ns1__CheckInAsset);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__CheckInAsset(soap, &soap_tmp___ns1__CheckInAsset, "-ns1:CheckInAsset", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__CheckInAsset(soap, &soap_tmp___ns1__CheckInAsset, "-ns1:CheckInAsset", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns3__CheckInAssetResponse)
		return soap_closesock(soap);
	ns3__CheckInAssetResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns3__CheckInAssetResponse->soap_get(soap, "ns3:CheckInAssetResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__DownloadVersion(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns3__DownloadVersion *ns3__DownloadVersion, _ns3__DownloadVersionResponse *ns3__DownloadVersionResponse)
{	struct __ns1__DownloadVersion soap_tmp___ns1__DownloadVersion;
	if (!soap_endpoint)
		soap_endpoint = "https://rajkumars/iZINE.Web.MVC/server.svc";
	if (!soap_action)
		soap_action = "http://izine-publish.net/server/DownloadVersion";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__DownloadVersion.ns3__DownloadVersion = ns3__DownloadVersion;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__DownloadVersion(soap, &soap_tmp___ns1__DownloadVersion);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__DownloadVersion(soap, &soap_tmp___ns1__DownloadVersion, "-ns1:DownloadVersion", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__DownloadVersion(soap, &soap_tmp___ns1__DownloadVersion, "-ns1:DownloadVersion", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns3__DownloadVersionResponse)
		return soap_closesock(soap);
	ns3__DownloadVersionResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns3__DownloadVersionResponse->soap_get(soap, "ns3:DownloadVersionResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

#if defined(__BORLANDC__)
#pragma option pop
#pragma option pop
#endif

/* End of soapClient.cpp */
