/* soapBasicHttpBinding_USCOREserverProxy.h
   Generated by gSOAP 2.7.13 from server.h
   Copyright(C) 2000-2009, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#ifndef soapBasicHttpBinding_USCOREserverProxy_H
#define soapBasicHttpBinding_USCOREserverProxy_H
#include "soapH.h"
class BasicHttpBinding_USCOREserver
{   public:
	/// Runtime engine context allocated in constructor
	struct soap *soap;
	/// Endpoint URL of service 'BasicHttpBinding_USCOREserver' (change as needed)
	const char *endpoint;
	/// Constructor allocates soap engine context, sets default endpoint URL, and sets namespace mapping table
	BasicHttpBinding_USCOREserver()
	{ soap = soap_new(); endpoint = "https://redv106/izine/server.svc"; if (soap && !soap->namespaces) { static const struct Namespace namespaces[] = 
{
	{"SOAP-ENV", "http://schemas.xmlsoap.org/soap/envelope/", "http://www.w3.org/*/soap-envelope", NULL},
	{"SOAP-ENC", "http://schemas.xmlsoap.org/soap/encoding/", "http://www.w3.org/*/soap-encoding", NULL},
	{"xsi", "http://www.w3.org/2001/XMLSchema-instance", "http://www.w3.org/*/XMLSchema-instance", NULL},
	{"xsd", "http://www.w3.org/2001/XMLSchema", "http://www.w3.org/*/XMLSchema", NULL},
	{"wsa", "http://schemas.xmlsoap.org/ws/2004/08/addressing", NULL, NULL},
	{"c14n", "http://www.w3.org/2001/10/xml-exc-c14n#", NULL, NULL},
	{"wsu", "http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd", NULL, NULL},
	{"ds", "http://www.w3.org/2000/09/xmldsig#", NULL, NULL},
	{"wsse", "http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd", NULL, NULL},
	{"wsrp", "http://schemas.xmlsoap.org/rp/", NULL, NULL},
	{"xop", "http://www.w3.org/2004/08/xop/include", NULL, NULL},
	{"ns4", "http://schemas.microsoft.com/2003/10/Serialization/", NULL, NULL},
	{"ns5", "http://schemas.microsoft.com/2003/10/Serialization/Arrays", NULL, NULL},
	{"ns6", "http://schemas.datacontract.org/2004/07/iZINE.Web.Server", NULL, NULL},
	{"ns1", "http://tempuri.org/", NULL, NULL},
	{"ns3", "http://izine-publish.net/", NULL, NULL},
	{NULL, NULL, NULL, NULL}
};
	soap->namespaces = namespaces; } };
	/// Destructor frees deserialized data and soap engine context
	virtual ~BasicHttpBinding_USCOREserver() { if (soap) { soap_destroy(soap); soap_end(soap); soap_free(soap); } };
	/// Invoke 'GetLock' of service 'CustomBinding_USCOREserver' and return error code (or SOAP_OK)
	virtual int __ns1__GetLock(_ns3__GetLock *ns3__GetLock, _ns3__GetLockResponse *ns3__GetLockResponse) { return soap ? soap_call___ns1__GetLock(soap, endpoint, NULL, ns3__GetLock, ns3__GetLockResponse) : SOAP_EOM; };
	/// Invoke 'CheckInAsset' of service 'CustomBinding_USCOREserver' and return error code (or SOAP_OK)
	virtual int __ns1__CheckInAsset(_ns3__CheckInAsset *ns3__CheckInAsset, _ns3__CheckInAssetResponse *ns3__CheckInAssetResponse) { return soap ? soap_call___ns1__CheckInAsset(soap, endpoint, NULL, ns3__CheckInAsset, ns3__CheckInAssetResponse) : SOAP_EOM; };
	/// Invoke 'DownloadVersion' of service 'CustomBinding_USCOREserver' and return error code (or SOAP_OK)
	virtual int __ns1__DownloadVersion(_ns3__DownloadVersion *ns3__DownloadVersion, _ns3__DownloadVersionResponse *ns3__DownloadVersionResponse) { return soap ? soap_call___ns1__DownloadVersion(soap, endpoint, NULL, ns3__DownloadVersion, ns3__DownloadVersionResponse) : SOAP_EOM; };
	/// Invoke 'Login' of service 'CustomBinding_USCOREserver' and return error code (or SOAP_OK)
	virtual int __ns1__Login(_ns3__Login *ns3__Login, _ns3__LoginResponse *ns3__LoginResponse) { return soap ? soap_call___ns1__Login(soap, endpoint, NULL, ns3__Login, ns3__LoginResponse) : SOAP_EOM; };
	/// Invoke 'GetStatusList_Old' of service 'CustomBinding_USCOREserver' and return error code (or SOAP_OK)
	virtual int __ns1__GetStatusList_USCOREOld(_ns3__GetStatusList_USCOREOld *ns3__GetStatusList_USCOREOld, _ns3__GetStatusList_USCOREOldResponse *ns3__GetStatusList_USCOREOldResponse) { return soap ? soap_call___ns1__GetStatusList_USCOREOld(soap, endpoint, NULL, ns3__GetStatusList_USCOREOld, ns3__GetStatusList_USCOREOldResponse) : SOAP_EOM; };
	/// Invoke 'GetTitleList' of service 'CustomBinding_USCOREserver' and return error code (or SOAP_OK)
	virtual int __ns1__GetTitleList(_ns3__GetTitleList *ns3__GetTitleList, _ns3__GetTitleListResponse *ns3__GetTitleListResponse) { return soap ? soap_call___ns1__GetTitleList(soap, endpoint, NULL, ns3__GetTitleList, ns3__GetTitleListResponse) : SOAP_EOM; };
	/// Invoke 'GetRole' of service 'CustomBinding_USCOREserver' and return error code (or SOAP_OK)
	virtual int __ns1__GetRole(_ns3__GetRole *ns3__GetRole, _ns3__GetRoleResponse *ns3__GetRoleResponse) { return soap ? soap_call___ns1__GetRole(soap, endpoint, NULL, ns3__GetRole, ns3__GetRoleResponse) : SOAP_EOM; };
	/// Invoke 'GetCommentList' of service 'CustomBinding_USCOREserver' and return error code (or SOAP_OK)
	virtual int __ns1__GetCommentList(_ns3__GetCommentList *ns3__GetCommentList, _ns3__GetCommentListResponse *ns3__GetCommentListResponse) { return soap ? soap_call___ns1__GetCommentList(soap, endpoint, NULL, ns3__GetCommentList, ns3__GetCommentListResponse) : SOAP_EOM; };
	/// Invoke 'GetTags' of service 'CustomBinding_USCOREserver' and return error code (or SOAP_OK)
	virtual int __ns1__GetTags(_ns3__GetTags *ns3__GetTags, _ns3__GetTagsResponse *ns3__GetTagsResponse) { return soap ? soap_call___ns1__GetTags(soap, endpoint, NULL, ns3__GetTags, ns3__GetTagsResponse) : SOAP_EOM; };
	/// Invoke 'GetShelveList' of service 'CustomBinding_USCOREserver' and return error code (or SOAP_OK)
	virtual int __ns1__GetShelveList(_ns3__GetShelveList *ns3__GetShelveList, _ns3__GetShelveListResponse *ns3__GetShelveListResponse) { return soap ? soap_call___ns1__GetShelveList(soap, endpoint, NULL, ns3__GetShelveList, ns3__GetShelveListResponse) : SOAP_EOM; };
	/// Invoke 'Logoff' of service 'CustomBinding_USCOREserver' and return error code (or SOAP_OK)
	virtual int __ns1__Logoff(_ns3__Logoff *ns3__Logoff, _ns3__LogoffResponse *ns3__LogoffResponse) { return soap ? soap_call___ns1__Logoff(soap, endpoint, NULL, ns3__Logoff, ns3__LogoffResponse) : SOAP_EOM; };
	/// Invoke 'GetUser' of service 'CustomBinding_USCOREserver' and return error code (or SOAP_OK)
	virtual int __ns1__GetUser(_ns3__GetUser *ns3__GetUser, _ns3__GetUserResponse *ns3__GetUserResponse) { return soap ? soap_call___ns1__GetUser(soap, endpoint, NULL, ns3__GetUser, ns3__GetUserResponse) : SOAP_EOM; };
	/// Invoke 'GetThumbnail' of service 'CustomBinding_USCOREserver' and return error code (or SOAP_OK)
	virtual int __ns1__GetThumbnail(_ns3__GetThumbnail *ns3__GetThumbnail, _ns3__GetThumbnailResponse *ns3__GetThumbnailResponse) { return soap ? soap_call___ns1__GetThumbnail(soap, endpoint, NULL, ns3__GetThumbnail, ns3__GetThumbnailResponse) : SOAP_EOM; };
	/// Invoke 'LockAsset' of service 'CustomBinding_USCOREserver' and return error code (or SOAP_OK)
	virtual int __ns1__LockAsset(_ns3__LockAsset *ns3__LockAsset, _ns3__LockAssetResponse *ns3__LockAssetResponse) { return soap ? soap_call___ns1__LockAsset(soap, endpoint, NULL, ns3__LockAsset, ns3__LockAssetResponse) : SOAP_EOM; };
	/// Invoke 'UnlockAsset' of service 'CustomBinding_USCOREserver' and return error code (or SOAP_OK)
	virtual int __ns1__UnlockAsset(_ns3__UnlockAsset *ns3__UnlockAsset, _ns3__UnlockAssetResponse *ns3__UnlockAssetResponse) { return soap ? soap_call___ns1__UnlockAsset(soap, endpoint, NULL, ns3__UnlockAsset, ns3__UnlockAssetResponse) : SOAP_EOM; };
	/// Invoke 'GetLock_Old' of service 'CustomBinding_USCOREserver' and return error code (or SOAP_OK)
	virtual int __ns1__GetLock_USCOREOld(_ns3__GetLock_USCOREOld *ns3__GetLock_USCOREOld, _ns3__GetLock_USCOREOldResponse *ns3__GetLock_USCOREOldResponse) { return soap ? soap_call___ns1__GetLock_USCOREOld(soap, endpoint, NULL, ns3__GetLock_USCOREOld, ns3__GetLock_USCOREOldResponse) : SOAP_EOM; };
	/// Invoke 'DeleteAsset' of service 'CustomBinding_USCOREserver' and return error code (or SOAP_OK)
	virtual int __ns1__DeleteAsset(_ns3__DeleteAsset *ns3__DeleteAsset, _ns3__DeleteAssetResponse *ns3__DeleteAssetResponse) { return soap ? soap_call___ns1__DeleteAsset(soap, endpoint, NULL, ns3__DeleteAsset, ns3__DeleteAssetResponse) : SOAP_EOM; };
	/// Invoke 'CreateAsset' of service 'CustomBinding_USCOREserver' and return error code (or SOAP_OK)
	virtual int __ns1__CreateAsset(_ns3__CreateAsset *ns3__CreateAsset, _ns3__CreateAssetResponse *ns3__CreateAssetResponse) { return soap ? soap_call___ns1__CreateAsset(soap, endpoint, NULL, ns3__CreateAsset, ns3__CreateAssetResponse) : SOAP_EOM; };
	/// Invoke 'UpdateAsset_Old' of service 'CustomBinding_USCOREserver' and return error code (or SOAP_OK)
	virtual int __ns1__UpdateAsset_USCOREOld(_ns3__UpdateAsset_USCOREOld *ns3__UpdateAsset_USCOREOld, _ns3__UpdateAsset_USCOREOldResponse *ns3__UpdateAsset_USCOREOldResponse) { return soap ? soap_call___ns1__UpdateAsset_USCOREOld(soap, endpoint, NULL, ns3__UpdateAsset_USCOREOld, ns3__UpdateAsset_USCOREOldResponse) : SOAP_EOM; };
	/// Invoke 'UpdateAssetName' of service 'CustomBinding_USCOREserver' and return error code (or SOAP_OK)
	virtual int __ns1__UpdateAssetName(_ns3__UpdateAssetName *ns3__UpdateAssetName, _ns3__UpdateAssetNameResponse *ns3__UpdateAssetNameResponse) { return soap ? soap_call___ns1__UpdateAssetName(soap, endpoint, NULL, ns3__UpdateAssetName, ns3__UpdateAssetNameResponse) : SOAP_EOM; };
	/// Invoke 'GetAsset' of service 'CustomBinding_USCOREserver' and return error code (or SOAP_OK)
	virtual int __ns1__GetAsset(_ns3__GetAsset *ns3__GetAsset, _ns3__GetAssetResponse *ns3__GetAssetResponse) { return soap ? soap_call___ns1__GetAsset(soap, endpoint, NULL, ns3__GetAsset, ns3__GetAssetResponse) : SOAP_EOM; };
	/// Invoke 'UploadPDF' of service 'CustomBinding_USCOREserver' and return error code (or SOAP_OK)
	virtual int __ns1__UploadPDF(_ns3__UploadPDF *ns3__UploadPDF, _ns3__UploadPDFResponse *ns3__UploadPDFResponse) { return soap ? soap_call___ns1__UploadPDF(soap, endpoint, NULL, ns3__UploadPDF, ns3__UploadPDFResponse) : SOAP_EOM; };
	/// Invoke 'UploadPage' of service 'CustomBinding_USCOREserver' and return error code (or SOAP_OK)
	virtual int __ns1__UploadPage(_ns3__UploadPage *ns3__UploadPage, _ns3__UploadPageResponse *ns3__UploadPageResponse) { return soap ? soap_call___ns1__UploadPage(soap, endpoint, NULL, ns3__UploadPage, ns3__UploadPageResponse) : SOAP_EOM; };
	/// Invoke 'UploadVersion' of service 'CustomBinding_USCOREserver' and return error code (or SOAP_OK)
	virtual int __ns1__UploadVersion(_ns3__UploadVersion *ns3__UploadVersion, _ns3__UploadVersionResponse *ns3__UploadVersionResponse) { return soap ? soap_call___ns1__UploadVersion(soap, endpoint, NULL, ns3__UploadVersion, ns3__UploadVersionResponse) : SOAP_EOM; };
	/// Invoke 'DownloadVersion_Old' of service 'CustomBinding_USCOREserver' and return error code (or SOAP_OK)
	virtual int __ns1__DownloadVersion_USCOREOld(_ns3__DownloadVersion_USCOREOld *ns3__DownloadVersion_USCOREOld, _ns3__DownloadVersion_USCOREOldResponse *ns3__DownloadVersion_USCOREOldResponse) { return soap ? soap_call___ns1__DownloadVersion_USCOREOld(soap, endpoint, NULL, ns3__DownloadVersion_USCOREOld, ns3__DownloadVersion_USCOREOldResponse) : SOAP_EOM; };
	/// Invoke 'UnlinkAsset' of service 'CustomBinding_USCOREserver' and return error code (or SOAP_OK)
	virtual int __ns1__UnlinkAsset(_ns3__UnlinkAsset *ns3__UnlinkAsset, _ns3__UnlinkAssetResponse *ns3__UnlinkAssetResponse) { return soap ? soap_call___ns1__UnlinkAsset(soap, endpoint, NULL, ns3__UnlinkAsset, ns3__UnlinkAssetResponse) : SOAP_EOM; };
	/// Invoke 'CheckInAsset_Old' of service 'CustomBinding_USCOREserver' and return error code (or SOAP_OK)
	virtual int __ns1__CheckInAsset_USCOREOld(_ns3__CheckInAsset_USCOREOld *ns3__CheckInAsset_USCOREOld, _ns3__CheckInAsset_USCOREOldResponse *ns3__CheckInAsset_USCOREOldResponse) { return soap ? soap_call___ns1__CheckInAsset_USCOREOld(soap, endpoint, NULL, ns3__CheckInAsset_USCOREOld, ns3__CheckInAsset_USCOREOldResponse) : SOAP_EOM; };
	/// Invoke 'RelinkAsset' of service 'CustomBinding_USCOREserver' and return error code (or SOAP_OK)
	virtual int __ns1__RelinkAsset(_ns3__RelinkAsset *ns3__RelinkAsset, _ns3__RelinkAssetResponse *ns3__RelinkAssetResponse) { return soap ? soap_call___ns1__RelinkAsset(soap, endpoint, NULL, ns3__RelinkAsset, ns3__RelinkAssetResponse) : SOAP_EOM; };
	/// Invoke 'CreateTask' of service 'CustomBinding_USCOREserver' and return error code (or SOAP_OK)
	virtual int __ns1__CreateTask(_ns3__CreateTask *ns3__CreateTask, _ns3__CreateTaskResponse *ns3__CreateTaskResponse) { return soap ? soap_call___ns1__CreateTask(soap, endpoint, NULL, ns3__CreateTask, ns3__CreateTaskResponse) : SOAP_EOM; };
	/// Invoke 'GetTasks' of service 'CustomBinding_USCOREserver' and return error code (or SOAP_OK)
	virtual int __ns1__GetTasks(_ns3__GetTasks *ns3__GetTasks, _ns3__GetTasksResponse *ns3__GetTasksResponse) { return soap ? soap_call___ns1__GetTasks(soap, endpoint, NULL, ns3__GetTasks, ns3__GetTasksResponse) : SOAP_EOM; };
	/// Invoke 'CheckOutAsset' of service 'CustomBinding_USCOREserver' and return error code (or SOAP_OK)
	virtual int __ns1__CheckOutAsset(_ns3__CheckOutAsset *ns3__CheckOutAsset, _ns3__CheckOutAssetResponse *ns3__CheckOutAssetResponse) { return soap ? soap_call___ns1__CheckOutAsset(soap, endpoint, NULL, ns3__CheckOutAsset, ns3__CheckOutAssetResponse) : SOAP_EOM; };
	/// Invoke 'GetEditionsByTitle' of service 'CustomBinding_USCOREserver' and return error code (or SOAP_OK)
	virtual int __ns1__GetEditionsByTitle(_ns3__GetEditionsByTitle *ns3__GetEditionsByTitle, _ns3__GetEditionsByTitleResponse *ns3__GetEditionsByTitleResponse) { return soap ? soap_call___ns1__GetEditionsByTitle(soap, endpoint, NULL, ns3__GetEditionsByTitle, ns3__GetEditionsByTitleResponse) : SOAP_EOM; };
	/// Invoke 'GetStatusByTitle' of service 'CustomBinding_USCOREserver' and return error code (or SOAP_OK)
	virtual int __ns1__GetStatusByTitle(_ns3__GetStatusByTitle *ns3__GetStatusByTitle, _ns3__GetStatusByTitleResponse *ns3__GetStatusByTitleResponse) { return soap ? soap_call___ns1__GetStatusByTitle(soap, endpoint, NULL, ns3__GetStatusByTitle, ns3__GetStatusByTitleResponse) : SOAP_EOM; };
	/// Invoke 'GetAssetList' of service 'CustomBinding_USCOREserver' and return error code (or SOAP_OK)
	virtual int __ns1__GetAssetList(_ns3__GetAssetList *ns3__GetAssetList, _ns3__GetAssetListResponse *ns3__GetAssetListResponse) { return soap ? soap_call___ns1__GetAssetList(soap, endpoint, NULL, ns3__GetAssetList, ns3__GetAssetListResponse) : SOAP_EOM; };
	/// Invoke 'UpdateAsset' of service 'CustomBinding_USCOREserver' and return error code (or SOAP_OK)
	virtual int __ns1__UpdateAsset(_ns3__UpdateAsset *ns3__UpdateAsset, _ns3__UpdateAssetResponse *ns3__UpdateAssetResponse) { return soap ? soap_call___ns1__UpdateAsset(soap, endpoint, NULL, ns3__UpdateAsset, ns3__UpdateAssetResponse) : SOAP_EOM; };
};
#endif
