/* soapServiceSoapObject.h
   Generated by gSOAP 2.7.12 from service.h
   Copyright(C) 2000-2008, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#ifndef soapServiceSoapObject_H
#define soapServiceSoapObject_H
#include "soapH.h"

/******************************************************************************\
 *                                                                            *
 * Service Object                                                             *
 *                                                                            *
\******************************************************************************/

class ServiceSoapService : public soap
{    public:
	ServiceSoapService()
	{ static const struct Namespace namespaces[] =
{
	{"SOAP-ENV", "http://www.w3.org/2003/05/soap-envelope", "http://www.w3.org/2003/05/soap-envelope", NULL},
	{"SOAP-ENC", "http://www.w3.org/2003/05/soap-encoding", "http://www.w3.org/2003/05/soap-encoding", NULL},
	{"xsi", "http://www.w3.org/2001/XMLSchema-instance", "http://www.w3.org/*/XMLSchema-instance", NULL},
	{"xsd", "http://www.w3.org/2001/XMLSchema", "http://www.w3.org/*/XMLSchema", NULL},
	{"ns2", "http://microsoft.com/wsdl/types/", NULL, NULL},
	{"ns3", "http://izine-publish.net/server/ServiceSoap", NULL, NULL},
	{"ns1", "http://izine-publish.net/server/", NULL, NULL},
	{"ns4", "http://izine-publish.net/server/ServiceSoap12", NULL, NULL},
	{NULL, NULL, NULL, NULL}
};
	if (!this->namespaces) this->namespaces = namespaces; };
	virtual ~ServiceSoapService() { };
	/// Bind service to port (returns master socket or SOAP_INVALID_SOCKET)
	virtual	SOAP_SOCKET bind(const char *host, int port, int backlog) { return soap_bind(this, host, port, backlog); };
	/// Accept next request (returns socket or SOAP_INVALID_SOCKET)
	virtual	SOAP_SOCKET accept() { return soap_accept(this); };
	/// Serve this request (returns error code or SOAP_OK)
	virtual	int serve() { return soap_serve(this); };
};

/******************************************************************************\
 *                                                                            *
 * Service Operations (you should define these globally)                      *
 *                                                                            *
\******************************************************************************/


SOAP_FMAC5 int SOAP_FMAC6 __ns3__Ping(struct soap*, _ns1__Ping *ns1__Ping, _ns1__PingResponse *ns1__PingResponse);

SOAP_FMAC5 int SOAP_FMAC6 __ns3__GetStatusList(struct soap*, _ns1__GetStatusList *ns1__GetStatusList, _ns1__GetStatusListResponse *ns1__GetStatusListResponse);

SOAP_FMAC5 int SOAP_FMAC6 __ns3__GetTitleList(struct soap*, _ns1__GetTitleList *ns1__GetTitleList, _ns1__GetTitleListResponse *ns1__GetTitleListResponse);

SOAP_FMAC5 int SOAP_FMAC6 __ns3__GetRole(struct soap*, _ns1__GetRole *ns1__GetRole, _ns1__GetRoleResponse *ns1__GetRoleResponse);

SOAP_FMAC5 int SOAP_FMAC6 __ns3__GetAssetList(struct soap*, _ns1__GetAssetList *ns1__GetAssetList, _ns1__GetAssetListResponse *ns1__GetAssetListResponse);

SOAP_FMAC5 int SOAP_FMAC6 __ns3__GetShelveList(struct soap*, _ns1__GetShelveList *ns1__GetShelveList, _ns1__GetShelveListResponse *ns1__GetShelveListResponse);

SOAP_FMAC5 int SOAP_FMAC6 __ns3__Logoff(struct soap*, _ns1__Logoff *ns1__Logoff, _ns1__LogoffResponse *ns1__LogoffResponse);

SOAP_FMAC5 int SOAP_FMAC6 __ns3__Login(struct soap*, _ns1__Login *ns1__Login, _ns1__LoginResponse *ns1__LoginResponse);

SOAP_FMAC5 int SOAP_FMAC6 __ns3__GetThumbnail(struct soap*, _ns1__GetThumbnail *ns1__GetThumbnail, _ns1__GetThumbnailResponse *ns1__GetThumbnailResponse);

SOAP_FMAC5 int SOAP_FMAC6 __ns3__Lock(struct soap*, _ns1__Lock *ns1__Lock, _ns1__LockResponse *ns1__LockResponse);

SOAP_FMAC5 int SOAP_FMAC6 __ns3__Unlock(struct soap*, _ns1__Unlock *ns1__Unlock, _ns1__UnlockResponse *ns1__UnlockResponse);

SOAP_FMAC5 int SOAP_FMAC6 __ns3__GetLock(struct soap*, _ns1__GetLock *ns1__GetLock, _ns1__GetLockResponse *ns1__GetLockResponse);

SOAP_FMAC5 int SOAP_FMAC6 __ns3__DeleteAsset(struct soap*, _ns1__DeleteAsset *ns1__DeleteAsset, _ns1__DeleteAssetResponse *ns1__DeleteAssetResponse);

SOAP_FMAC5 int SOAP_FMAC6 __ns3__CreateAsset(struct soap*, _ns1__CreateAsset *ns1__CreateAsset, _ns1__CreateAssetResponse *ns1__CreateAssetResponse);

SOAP_FMAC5 int SOAP_FMAC6 __ns3__UpdateAssetName(struct soap*, _ns1__UpdateAssetName *ns1__UpdateAssetName, _ns1__UpdateAssetNameResponse *ns1__UpdateAssetNameResponse);

SOAP_FMAC5 int SOAP_FMAC6 __ns3__GetAsset(struct soap*, _ns1__GetAsset *ns1__GetAsset, _ns1__GetAssetResponse *ns1__GetAssetResponse);

SOAP_FMAC5 int SOAP_FMAC6 __ns3__UploadVersion(struct soap*, _ns1__UploadVersion *ns1__UploadVersion, _ns1__UploadVersionResponse *ns1__UploadVersionResponse);

SOAP_FMAC5 int SOAP_FMAC6 __ns3__UploadThumbnail(struct soap*, _ns1__UploadThumbnail *ns1__UploadThumbnail, _ns1__UploadThumbnailResponse *ns1__UploadThumbnailResponse);

SOAP_FMAC5 int SOAP_FMAC6 __ns3__DownloadVersion(struct soap*, _ns1__DownloadVersion *ns1__DownloadVersion, _ns1__DownloadVersionResponse *ns1__DownloadVersionResponse);

SOAP_FMAC5 int SOAP_FMAC6 __ns3__UnlinkAsset(struct soap*, _ns1__UnlinkAsset *ns1__UnlinkAsset, _ns1__UnlinkAssetResponse *ns1__UnlinkAssetResponse);

SOAP_FMAC5 int SOAP_FMAC6 __ns3__CheckInAsset(struct soap*, _ns1__CheckInAsset *ns1__CheckInAsset, _ns1__CheckInAssetResponse *ns1__CheckInAssetResponse);

SOAP_FMAC5 int SOAP_FMAC6 __ns3__RelinkAsset(struct soap*, _ns1__RelinkAsset *ns1__RelinkAsset, _ns1__RelinkAssetResponse *ns1__RelinkAssetResponse);

SOAP_FMAC5 int SOAP_FMAC6 __ns3__CheckOutAsset(struct soap*, _ns1__CheckOutAsset *ns1__CheckOutAsset, _ns1__CheckOutAssetResponse *ns1__CheckOutAssetResponse);

SOAP_FMAC5 int SOAP_FMAC6 __ns4__Ping(struct soap*, _ns1__Ping *ns1__Ping, _ns1__PingResponse *ns1__PingResponse);

SOAP_FMAC5 int SOAP_FMAC6 __ns4__GetStatusList(struct soap*, _ns1__GetStatusList *ns1__GetStatusList, _ns1__GetStatusListResponse *ns1__GetStatusListResponse);

SOAP_FMAC5 int SOAP_FMAC6 __ns4__GetTitleList(struct soap*, _ns1__GetTitleList *ns1__GetTitleList, _ns1__GetTitleListResponse *ns1__GetTitleListResponse);

SOAP_FMAC5 int SOAP_FMAC6 __ns4__GetRole(struct soap*, _ns1__GetRole *ns1__GetRole, _ns1__GetRoleResponse *ns1__GetRoleResponse);

SOAP_FMAC5 int SOAP_FMAC6 __ns4__GetAssetList(struct soap*, _ns1__GetAssetList *ns1__GetAssetList, _ns1__GetAssetListResponse *ns1__GetAssetListResponse);

SOAP_FMAC5 int SOAP_FMAC6 __ns4__GetShelveList(struct soap*, _ns1__GetShelveList *ns1__GetShelveList, _ns1__GetShelveListResponse *ns1__GetShelveListResponse);

SOAP_FMAC5 int SOAP_FMAC6 __ns4__Logoff(struct soap*, _ns1__Logoff *ns1__Logoff, _ns1__LogoffResponse *ns1__LogoffResponse);

SOAP_FMAC5 int SOAP_FMAC6 __ns4__Login(struct soap*, _ns1__Login *ns1__Login, _ns1__LoginResponse *ns1__LoginResponse);

SOAP_FMAC5 int SOAP_FMAC6 __ns4__GetThumbnail(struct soap*, _ns1__GetThumbnail *ns1__GetThumbnail, _ns1__GetThumbnailResponse *ns1__GetThumbnailResponse);

SOAP_FMAC5 int SOAP_FMAC6 __ns4__Lock(struct soap*, _ns1__Lock *ns1__Lock, _ns1__LockResponse *ns1__LockResponse);

SOAP_FMAC5 int SOAP_FMAC6 __ns4__Unlock(struct soap*, _ns1__Unlock *ns1__Unlock, _ns1__UnlockResponse *ns1__UnlockResponse);

SOAP_FMAC5 int SOAP_FMAC6 __ns4__GetLock(struct soap*, _ns1__GetLock *ns1__GetLock, _ns1__GetLockResponse *ns1__GetLockResponse);

SOAP_FMAC5 int SOAP_FMAC6 __ns4__DeleteAsset(struct soap*, _ns1__DeleteAsset *ns1__DeleteAsset, _ns1__DeleteAssetResponse *ns1__DeleteAssetResponse);

SOAP_FMAC5 int SOAP_FMAC6 __ns4__CreateAsset(struct soap*, _ns1__CreateAsset *ns1__CreateAsset, _ns1__CreateAssetResponse *ns1__CreateAssetResponse);

SOAP_FMAC5 int SOAP_FMAC6 __ns4__UpdateAssetName(struct soap*, _ns1__UpdateAssetName *ns1__UpdateAssetName, _ns1__UpdateAssetNameResponse *ns1__UpdateAssetNameResponse);

SOAP_FMAC5 int SOAP_FMAC6 __ns4__GetAsset(struct soap*, _ns1__GetAsset *ns1__GetAsset, _ns1__GetAssetResponse *ns1__GetAssetResponse);

SOAP_FMAC5 int SOAP_FMAC6 __ns4__UploadVersion(struct soap*, _ns1__UploadVersion *ns1__UploadVersion, _ns1__UploadVersionResponse *ns1__UploadVersionResponse);

SOAP_FMAC5 int SOAP_FMAC6 __ns4__UploadThumbnail(struct soap*, _ns1__UploadThumbnail *ns1__UploadThumbnail, _ns1__UploadThumbnailResponse *ns1__UploadThumbnailResponse);

SOAP_FMAC5 int SOAP_FMAC6 __ns4__DownloadVersion(struct soap*, _ns1__DownloadVersion *ns1__DownloadVersion, _ns1__DownloadVersionResponse *ns1__DownloadVersionResponse);

SOAP_FMAC5 int SOAP_FMAC6 __ns4__UnlinkAsset(struct soap*, _ns1__UnlinkAsset *ns1__UnlinkAsset, _ns1__UnlinkAssetResponse *ns1__UnlinkAssetResponse);

SOAP_FMAC5 int SOAP_FMAC6 __ns4__CheckInAsset(struct soap*, _ns1__CheckInAsset *ns1__CheckInAsset, _ns1__CheckInAssetResponse *ns1__CheckInAssetResponse);

SOAP_FMAC5 int SOAP_FMAC6 __ns4__RelinkAsset(struct soap*, _ns1__RelinkAsset *ns1__RelinkAsset, _ns1__RelinkAssetResponse *ns1__RelinkAssetResponse);

SOAP_FMAC5 int SOAP_FMAC6 __ns4__CheckOutAsset(struct soap*, _ns1__CheckOutAsset *ns1__CheckOutAsset, _ns1__CheckOutAssetResponse *ns1__CheckOutAssetResponse);

#endif
